private _loadout = [];
//////////////////////////////////////////////////

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","SMA_ANPEQ15_BLK","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["tft8_combat_fatigue_ocp_rs_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["adv_aceSplint_splint",4],["ACE_tourniquet",4],["rhsusf_ANPVS_15",1]]],["tft8_ciras_ocp_operator",[["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_salineIV_500",1],["SMA_SFFL_BLK",1],["ACE_SpraypaintGreen",1],["ACE_NVG_Gen4",1],["rhsusf_mag_15Rnd_9x19_JHP",1,15],["SmokeShell",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShellGreen",2,1],["rhs_mag_30Rnd_556x45_M855_PMAG",10,30]]],["tft8_kitbag_ocp",[]],"tft8_ach_helmet_headset_ocp","rhsusf_oakley_goggles_blk",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["01 Rifleman", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m249_pip","rhsusf_acc_SF3P556","","rhsusf_acc_compm4",["rhsusf_200rnd_556x45_mixed_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["tft8_patrolcap_field",1],["rhsusf_mag_15Rnd_9x19_JHP",1,15]]],["tft8_ciras_ocp_556",[["SMA_SFFL_BLK",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_NVG_Gen4",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_200rnd_556x45_mixed_box",2,200],["rhs_mag_m67",2,1]]],["tft8_assaultpack_ocp",[["ACE_SpareBarrel",1,1],["rhsusf_200rnd_556x45_mixed_box",2,200]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["02 Auto Rifleman", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m16a4","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15side_bk","optic_AMS",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["ACE_RangeCard",1],["tft8_patrolcap_field",1],["rhsusf_mag_15Rnd_9x19_JHP",1,15]]],["tft8_ciras_ocp_556",[["SMA_SFFL_BLK",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["rhsusf_acc_nt4_black",1],["CUP_optic_AN_PVS_10",1],["ACE_NVG_Gen4",1],["ACE_Kestrel4500",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["rhsusf_mag_15Rnd_9x19_JHP",2,15]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Rangefinder","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["03 Marksman", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m4a1_carryhandle_m203S","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["rhs_mag_M441_HE",1],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["tft8_patrolcap_field",1],["rhsusf_mag_15Rnd_9x19_JHP",1,15]]],["tft8_ciras_ocp_556",[["SMA_SFFL_BLK",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_NVG_Gen4",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhs_mag_m67",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30]]],["tft8_assaultpack_ocp",[["rhs_mag_M441_HE",8,1],["UGL_FlareCIR_F",2,1],["UGL_FlareWhite_F",2,1],["rhs_mag_m713_Red",3,1]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["04 Grenadier", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],["launch_MRAWS_green_F","","","",["MRAWS_HEAT_F",1],[],""],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["tft8_patrolcap_field",1],["rhsusf_mag_15Rnd_9x19_JHP",1,15]]],["tft8_ciras_ocp_556",[["SMA_SFFL_BLK",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_NVG_Gen4",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhs_mag_m67",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30]]],["tft8_assaultpack_ocp",[["MRAWS_HEAT_F",2,1],["MRAWS_HE_F",1,1]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["05 Anti-Tank", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m4a1","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["tft8_patrolcap_field",1]]],["tft8_helipilot_vest",[["SMA_SFFL_BLK",1],["ACE_salineIV_500",1],["rhsusf_ANPVS_15",1],["SmokeShell",2,1],["Chemlight_blue",2,1],["Chemlight_red",1,1],["Chemlight_green",1,1],["ACE_HandFlare_White",1,1],["SmokeShellBlue",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["tft8_rt1523g_ocp",[]],"rhsusf_hgu56p_visor_green","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["06 Aircrew", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [[],[],[],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["tft8_patrolcap_field",1]]],["tft8_ciras_ocp_556",[["SMA_SFFL_BLK",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_NVG_Gen4",1],["SmokeShell",2,1],["SmokeShellGreen",2,1]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["07 Ranger On-Base", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [[],[],[],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["tft8_patrolcap_field",1]]],["tft8_helipilot_vest",[["SMA_SFFL_BLK",1],["ACE_salineIV_500",1],["rhsusf_ANPVS_15",1],["SmokeShell",2,1],["Chemlight_blue",2,1],["Chemlight_red",1,1],["Chemlight_green",1,1],["ACE_HandFlare_White",1,1],["SmokeShellBlue",1,1]]],["tft8_rt1523g_ocp",[]],"rhsusf_hgu56p_visor_green","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["08 Aviation On-Base", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["tft8_patrolcap_field",1],["rhsusf_mag_15Rnd_9x19_JHP",1,15]]],["tft8_ciras_ocp_556",[["SMA_SFFL_BLK",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_NVG_Gen4",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30]]],["B_Parachute",[]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["09 Parachutist", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [[],[],[],["US_uniform_full",[["adv_aceSplint_splint",4],["ACE_tourniquet",4],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["SMA_SFFL_BLK",1]]],[],[],"tft8_patrolcap_parade","milgp_f_tactical_khk",[],["ItemMap","ItemAndroid","TFAR_anprc152_3","ItemCompass","ItemWatch",""]];
["10 Parade RCT", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

/*

_loadout = loadout_code;
["11 loadout_name", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

*/