private _loadout = [];
//////////////////////////////////////////////////

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["US_uniform_rifleman",[["ACE_fieldDressing",4],["ACE_morphine",2],["ACE_tourniquet",4],["adv_aceSplint_splint",4],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["01 Rifleman", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m249_pip","","","rhsusf_acc_ELCAN",["rhsusf_200rnd_556x45_mixed_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["US_uniform_rifleman",[["ACE_fieldDressing",4],["ACE_morphine",2],["ACE_tourniquet",4],["adv_aceSplint_splint",4],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhsusf_200rnd_556x45_mixed_box",2,200],["HandGrenade",2,1]]],["tft8_assaultpack_ocp",[["ACE_SpareBarrel",1,1],["rhsusf_200rnd_556x45_mixed_box",2,200]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["02 Auto Rifleman", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m16a4","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","optic_AMS",["SMA_30Rnd_556x45_Mk262",30],[],"CUP_bipod_Harris_1A2_L_BLK"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["US_uniform_rifleman",[["ACE_fieldDressing",4],["ACE_morphine",2],["ACE_tourniquet",4],["adv_aceSplint_splint",4],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",2],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_premier_anpvs27",1],["CUP_muzzle_snds_M16",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["SMA_30Rnd_556x45_Mk262",7,30],["HandGrenade",2,1]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["03 Marksman", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m4_carryhandle_m203S","rhsusf_acc_SF3P556","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["US_uniform_rifleman",[["ACE_fieldDressing",4],["ACE_morphine",2],["ACE_tourniquet",4],["adv_aceSplint_splint",4],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["HandGrenade",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30]]],["tft8_assaultpack_ocp",[["1Rnd_HE_Grenade_shell",8,1],["UGL_FlareCIR_F",2,1],["UGL_FlareWhite_F",2,1],["1Rnd_SmokeRed_Grenade_shell",3,1],["1Rnd_Smoke_Grenade_shell",4,1]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["04 Grenadier", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],["launch_MRAWS_green_F","","","",["MRAWS_HEAT_F",1],[],""],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["US_uniform_rifleman",[["ACE_fieldDressing",4],["ACE_morphine",2],["ACE_tourniquet",4],["adv_aceSplint_splint",4],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_packingBandage",6],["ItemcTabHCam",1],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],["tft8_kitbag_ocp",[["MRAWS_HEAT_F",3,1],["MRAWS_HE_F",4,1]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["05 Anti-Tank", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [["rhs_weap_m4a1","","","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_cw2_uniform",[["ACE_tourniquet",4],["ACE_morphine",2],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_elasticBandage",6],["ACE_fieldDressing",4],["ACE_epinephrine",2],["ACE_MapTools",1],["ACE_EarPlugs",2],["adv_aceSplint_splint",4],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["tft8_helipilot_vest",[["rhsusf_ANPVS_15",1],["Patrol_capv2",1],["Chemlight_blue",2,1],["Chemlight_green",1,1],["Chemlight_red",1,1],["SmokeShell",2,1],["SmokeShellBlue",1,1],["ACE_HandFlare_White",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",4,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["tft8_rt1523g_ocp",[]],"rhsusf_hgu56p_visor_green","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["06 Aircrew", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [[],[],[],["US_uniform_rifleman",[["ACE_fieldDressing",4],["ACE_morphine",2],["ACE_tourniquet",4],["adv_aceSplint_splint",4],["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_epinephrine",2],["ACE_packingBandage",6],["ItemcTabHCam",1]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["07 Basic Rifleman Kit", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [[],[],[],["acu_jacket_cw2_uniform",[["ACE_tourniquet",4],["ACE_morphine",2],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_elasticBandage",6],["ACE_fieldDressing",4],["ACE_epinephrine",2],["ACE_MapTools",1],["ACE_EarPlugs",2],["adv_aceSplint_splint",4],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["tft8_helipilot_vest",[["rhsusf_ANPVS_15",1],["Patrol_capv2",1],["Chemlight_blue",2,1],["Chemlight_green",1,1],["Chemlight_red",1,1],["SmokeShell",2,1],["SmokeShellBlue",1,1],["ACE_HandFlare_White",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",4,30]]],["tft8_rt1523g_ocp",[]],"rhsusf_hgu56p_visor_green","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["08 Basic Aviation Kit", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

_loadout = [[],[],[],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_packingBandage",6],["adv_aceSplint_splint",4],["ACE_tourniquet",4]]],["V_ALiVE_Suicide_Vest",[["ACE_salineIV_500",1],["ACE_NVG_Gen4",1],["SmokeShellGreen",2,1],["SmokeShell",2,1]]],[],"Patrol_cap","",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["09 Parade RCT", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

/*

_loadout = REPLACEMEloadout_code ;
["10 REPLACEMEloadout_name", _loadout] remoteExecCall ["ace_arsenal_fnc_addDefaultLoadout", 0,true];

*/
